server:
  port: 7001

logging:
  level:
    root: INFO
    com.champlain: DEBUG

spring:
  config:
    activate:
      on-profile: default

  data:
    mongodb:
      port: 0
      database: students
  mongodb:
    embedded:
      version: 4.0.21

---
spring:
  config:
    activate:
      on-profile: integration
  data:
    mongodb:
      host: localhost
      port: 27017
      database: students
      username: user
      password: pwd
      authentication-database: admin


---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongodb1
      port: 27017
      database: students
      username: user
      password: pwd
      authentication-database: admin